### ISSUE TITLE
The watch face does not work if the weather is displayed

### ISSUE THREAD

**Issue by maksim77** [RyanDam/Infocal#15]
If the weather is displayed in one of the fields on the watch face, an error occurs.
Model: VA4
Firmvare Version: 5.10
Here are the logs:

```yaml
Error: Unexpected Type Error
Details: 'Failed invoking <symbol>'
Time: 2020-10-03T12:17:52Z
Part-Number: 006-B3225-00
Firmware-Version: '5.10'
Language-Code: eng
ConnectIQ-Version: 3.2.1
Store-Id: c97c4e34-55e4-4601-b5c2-45763bc481a2
Store-Version: 91
Filename: A7864634
Appname: Huwaii
Stack:
  - pc: 0x10001ae4
  - pc: 0x10009cf6
  - pc: 0x10005f58
  - pc: 0x10009eb4
  - pc: 0x100087d6
  - pc: 0x10008573
```
