### ISSUE TITLE
Out Of Memory Error on FR245M after firmware update 9.00 

### ISSUE THREAD

**Issue by mandelbroo** [RyanDam/Infocal#26]
Does not reproduce with a fresh install. But happens if anything got modified in the watchface settings

My favorite watchface! @RyanDam thanks for the work you've done!

```yaml
Error: Out Of Memory Error
Details: 'Failed invoking <symbol>'
Time: 2022-03-17T10:27:56Z
Part-Number: 006-B3077-00
Firmware-Version: '9.00'
Language-Code: eng
ConnectIQ-Version: 3.2.1
Store-Id: c97c4e34-55e4-4601-b5c2-45763bc481a2
Store-Version: 98
Filename: C3GK2657
Appname: Huwaii
Stack: 
  - pc: 0x10007f64
```
